#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""add namespace to variable table

Revision ID: b7d8e0ee5d09
Revises: a4c2fd67d16b
Create Date: 2020-01-23 22:13:50.329596

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b7d8e0ee5d09'
down_revision = 'a4c2fd67d16b'
branch_labels = None
depends_on = None


def upgrade():
    """Apply add namespace to variable table"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('namespace', sa.String(length=250), nullable=True))
        batch_op.create_unique_constraint('ck_unique_namespace_key', ['namespace', 'key'])

    # ### end Alembic commands ###


def downgrade():
    """Unapply add namespace to variable table"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variable', schema=None) as batch_op:
        batch_op.drop_constraint('ck_unique_namespace_key', type_='unique')
        batch_op.drop_column('namespace')

    # ### end Alembic commands ###
